name: Build and deploy Node.js app to Azure Web App - my-frontend-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        working-directory: ./frontend
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment (excluding node_modules)
        working-directory: ./frontend
        run: |
          zip -r release.zip server.js package.json build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d frontend

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.2
        with:
          app-name: 'my-frontend-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75AC8D35CE4A4213A950359D6C9CCAAC }}
          clean: true

      # - name: Create install_dependencies.sh
      #   run: |
      #     echo '#!/bin/bash' > install_dependencies.sh
      #     echo 'echo "Current directory: $(/bin/pwd)"' >> install_dependencies.sh
      #     echo 'npm cache clean --force' >> install_dependencies.sh
      #     echo 'npm i --production' >> install_dependencies.sh
      #     echo 'echo "Dependencies installed successfully."' >> install_dependencies.sh
      #     chmod +x install_dependencies.sh
  
      # - name: Upload install_dependencies.sh to Azure Web App via FTPS
      #   run: |
      #     curl -T install_dependencies.sh --ftp-create-dirs --ssl-reqd -u '${{ secrets.AZURE_FTPS_USERNAME }}:${{ secrets.AZURE_FTPS_PASSWORD }}' "ftps://waws-prod-yt1-069.ftp.azurewebsites.windows.net/site/wwwroot/frontend/install_dependencies.sh"

      - name: Execute npm i on Azure Web App
        run: |
          curl -X POST -u '$my-frontend-app:${{ secrets.AZURE_FTPS_PASSWORD }}' "https://my-frontend-app-eufggghjd0e3dcbt.scm.canadacentral-01.azurewebsites.net/api/command" -H "Content-Type: application/json" -d "{\"command\":\"bash -c \\\"cd /home/site/wwwroot/frontend && npm i --verbose\\\"\"}" --verbose
  